import { Navbar } from "@/components";
import "./globals.css";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Car Info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
